// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    HorizontalBox {
        Rectangle {
            background: red;
            width: 50px;
            height: 50px;
        }
        Rectangle {
            background: green;
            width: 50px;
            height: 50px;
        }
        Rectangle {
            background: blue;
            width: 50px;
            height: 50px;
        }
    }
}
